/**
 * SalesTracking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRoleDTO } from './userRoleDTO';
import { RoleClaimDTO } from './roleClaimDTO';


export interface RoleDTO { 
    id?: number;
    isActive?: boolean;
    createDate?: string;
    createBy?: string | null;
    updateDate?: string | null;
    updateBy?: string | null;
    roleName?: string | null;
    roleClaim?: Array<RoleClaimDTO> | null;
    userRole?: Array<UserRoleDTO> | null;
}

