/**
 * SalesTracking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentsDTO } from './paymentsDTO';
import { SalesDetailsDTO } from './salesDetailsDTO';


export interface SalesDTO { 
    id?: number;
    isActive?: boolean;
    createDate?: string;
    createBy?: string | null;
    updateDate?: string | null;
    updateBy?: string | null;
    customerId?: number;
    customerName?: string | null;
    transactionDate?: string;
    invoiceNo?: string | null;
    isApproved?: boolean;
    approvedDate?: string | null;
    approvedBy?: string | null;
    totalAmout?: number;
    totalPayment?: number;
    salesDetails?: Array<SalesDetailsDTO> | null;
    payments?: Array<PaymentsDTO> | null;
}

