/**
 * SalesTracking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StockPurchaseDetailsDTO } from './stockPurchaseDetailsDTO';
import { StockPurchasePaymentDTO } from './stockPurchasePaymentDTO';


export interface StockPurchaseDTO { 
    id?: number;
    isActive?: boolean;
    createDate?: string;
    createBy?: string | null;
    updateDate?: string | null;
    updateBy?: string | null;
    purchaseNo?: string | null;
    transactionDate?: string;
    isApproved?: boolean;
    approvedDate?: string;
    approvedBy?: string | null;
    totalAmount?: number;
    totalPayment?: number;
    stockPurchaseDetails?: Array<StockPurchaseDetailsDTO> | null;
    stockPurchasePayment?: Array<StockPurchasePaymentDTO> | null;
}

